apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vuemap

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: vuemap
  app.kubernetes.io/instance: vuemap
  app.kubernetes.io/part-of: vuemap
